# Environment (Secret): DJANGO_SUPERUSER_USERNAME ، DJANGO_SUPERUSER_PASSWORD
# تأكدي أن المتغيرات مفعّلة لـ "Build & Runtime" أو على الأقل Runtime
services:
  - type: web
    name: my-responsibilities
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && bash build.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
