# Generated by Django 6.0.1 on 2026-04-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('situation', 'ماذا أفعل؟ (situation)'), ('truefalse', 'صح أو خطأ (true/false)'), ('journey', 'رحلة المسؤولية (journey)')], db_index=True, max_length=20, verbose_name='وضع اللعب')),
                ('order', models.PositiveIntegerField(default=0, help_text='رقم أصغر = يظهر أولاً داخل نفس الوضع.', verbose_name='الترتيب')),
                ('prompt', models.TextField(help_text='يمكن استخدام أسطر متعددة (عربي/إنجليزي).', verbose_name='نص السؤال')),
                ('q_type', models.CharField(choices=[('mc', 'اختيار من متعدد'), ('text', 'إجابة نصية + معيار تقييم (rubric)'), ('true_false', 'صح/خطأ فقط')], default='mc', max_length=20, verbose_name='نوع السؤال')),
                ('choices_json', models.JSONField(blank=True, default=list, verbose_name='خيارات (للاختيار من متعدد)')),
                ('correct_indices', models.JSONField(blank=True, default=list, help_text='قائمة أرقام الخيارات الصحيحة مثل [0] أو [0,2]. فارغة لنوع "نص".', verbose_name='الفهارس الصحيحة')),
                ('correct_tf', models.BooleanField(blank=True, help_text='للوضع صح/خطأ فقط: يحدد إن كان «صح» هو الجواب الصحيح.', null=True, verbose_name='الإجابة الصحيحة (صح/خطأ)')),
                ('rubric_json', models.JSONField(blank=True, null=True, verbose_name='معيار التقييم (rubric)')),
            ],
            options={
                'verbose_name': 'سؤال',
                'verbose_name_plural': 'الأسئلة',
                'ordering': ['mode', 'order', 'id'],
            },
        ),
    ]
