# Generated by Django 6.0.1 on 2026-04-06 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('situation', 'ماذا أفعل؟'), ('truefalse', 'صح أو خطأ'), ('journey', 'رحلة المسؤولية')], db_index=True, max_length=20, verbose_name='وضع اللعب')),
                ('score', models.PositiveIntegerField(verbose_name='النقاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نتيجة لعب',
                'verbose_name_plural': 'نتائج اللعب',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='نبذة عنك')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بروفايل',
                'verbose_name_plural': 'البروفايلات',
            },
        ),
    ]
